# Generated by Django 3.1.4 on 2021-01-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
