# Generated by Django 3.1.4 on 2021-01-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_url_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='time',
            field=models.TimeField(),
        ),
    ]
