# Generated by Django 3.1.4 on 2021-01-08 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_auto_20210106_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='time',
        ),
        migrations.AddField(
            model_name='url',
            name='data',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
