# Generated by Django 3.1.4 on 2021-01-08 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0016_auto_20210108_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
