# Generated by Django 3.1.4 on 2021-01-08 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0017_auto_20210108_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
